server.port=8080
logging.level.root=INFO
spring.temporary-password=xxxxxxxx
spring.datasource.url=jdbc:postgresql://<host>:5432/<dbname>?currentSchema=db_srs&ApplicationName=srs_app
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=db_srs
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.flyway.enabled=true
spring.flyway.schemas=db_srs
spring.flyway.create-schemas=true
spring.flyway.locations=classpath:db/migration
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=10000
