app:
  efs:
    base-path: /app/anexos
spring:
  application:
    name: srs
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.sa-east-1.amazonaws.com/xxxxxxxxxxxxxx
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      file-size-threshold: 2MB